sudo: false

language: node_js

node_js:
  - "6"

cache:
  directories:
    - node_modules

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_install:
  - npm install -g npm@latest
  - npm install -g angular-cli@latest

install:

script:

notifications:
  slack: akveo:q559HckfZMSyZRb803aiLcjH
